service: rss

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  deploymentBucket:
    blockPublicAccess: true

functions:
  rss:
    handler: dist/app.handler
    events:
      - http:
          method: get
          path: /
